import { ConflictException, ForbiddenException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { AuthUser } from '../../common/types/auth-user';
import { PrismaService } from '../../common/prisma/prisma.service';
import { FinanceService } from './finance.service';
import { FINANCE_TENANT, FINANCE_USER } from './finance.domain';
const user: AuthUser = { id: FINANCE_USER, tenantId: FINANCE_TENANT, nome: 'Paloma', email: 'p@example.test', role: 'GERENTE', ativo: true };
const id = '11111111-1111-4111-8111-111111111111';
const rule = { id, tenant_id: FINANCE_TENANT, version: 1, total_bps: 50, distribution: [20, 10, 10, 5, 5], created_by: FINANCE_USER, created_at: new Date() };
const sale = { id, tenant_id: FINANCE_TENANT, source_type: 'manual', source_key: id, source_version: null, description: 'Test sale', amount: new Prisma.Decimal('20000000'), commission_total: new Prisma.Decimal('100000'), closed_on: new Date('2026-01-15'), rule_id: id, rule, version: 1, needs_review: false, cancelled: false, created_by: FINANCE_USER, created_at: new Date(), updated_at: new Date(), installments: [] };
function fixture() { const db = { financeRule: { findFirst: jest.fn().mockResolvedValue(rule), create: jest.fn() }, financeSale: { findUnique: jest.fn().mockResolvedValue(null), findFirst: jest.fn().mockResolvedValue(sale), create: jest.fn().mockResolvedValue(sale), update: jest.fn(), count: jest.fn().mockResolvedValue(0) }, financeInstallment: { createMany: jest.fn(), findMany: jest.fn().mockResolvedValue([]), findFirst: jest.fn(), update: jest.fn(), aggregate: jest.fn().mockResolvedValue({ _count: 0, _sum: { amount: null } }) }, financeAudit: { create: jest.fn() }, partnerDailyProduction: { findMany: jest.fn().mockResolvedValue([]) }, $transaction: jest.fn() }; db.$transaction.mockImplementation(async (fn: (tx: typeof db) => Promise<unknown>) => fn(db)); return { db, service: new FinanceService(db as unknown as PrismaService) }; }
describe('financial ledger', () => {
    it('generates manual installments atomically and preserves the rule snapshot', async () => { const f = fixture(); await f.service.manual(user, { requestId: id, description: 'Test sale', amount: '20000000', closed_on: '2026-01-15' }); expect(f.db.financeInstallment.createMany.mock.calls[0][0].data.map((i: {
        amount: string;
    }) => i.amount)).toEqual(['40000.00', '20000.00', '20000.00', '10000.00', '10000.00']); expect(f.db.financeAudit.create).toHaveBeenCalled(); expect(f.db.$transaction).toHaveBeenCalledWith(expect.any(Function), expect.objectContaining({ isolationLevel: 'Serializable' })); });
    it('retries a manual submission without generating duplicate installments', async () => { const f = fixture(); f.db.financeSale.findUnique.mockResolvedValue(sale); await f.service.manual(user, { requestId: id, description: 'Test sale', amount: '20000000', closed_on: '2026-01-15' }); expect(f.db.financeSale.create).not.toHaveBeenCalled(); expect(f.db.financeInstallment.createMany).not.toHaveBeenCalled(); });
    it('does not duplicate an imported source; flags changed amounts without overwriting paid history', async () => { const f = fixture(); f.db.partnerDailyProduction.findMany.mockResolvedValue([{ id, amount: new Prisma.Decimal(500), version: 2, date: new Date('2026-01-15'), partner: { name: 'Partner' } }]); f.db.financeSale.findUnique.mockResolvedValue({ ...sale, source_type: 'partner', source_version: 1 }); expect(await f.service.sync(user)).toEqual({ created: 0, review: 1 }); expect(f.db.financeSale.update).toHaveBeenCalledWith({ where: { id }, data: { needs_review: true, version: { increment: 1 } } }); expect(f.db.financeInstallment.update).not.toHaveBeenCalled(); });
    it('rejects stale edits and cancelling a sale with receipts', async () => { const f = fixture(); await expect(f.service.cancel(user, id, { expectedVersion: 2 })).rejects.toBeInstanceOf(ConflictException); f.db.financeSale.findFirst.mockResolvedValue({ ...sale, installments: [{ received_on: new Date() }] }); await expect(f.service.cancel(user, id, { expectedVersion: 1 })).rejects.toThrow('parcelas recebidas'); expect(f.db.financeSale.update).not.toHaveBeenCalled(); });
    it('separates cash received this month from commissions due this month', async () => { const f = fixture(); const base = { id, tenant_id: FINANCE_TENANT, sale_id: id, number: 1, rate_bps: 20, due_overridden: false, received_by: null, version: 1, updated_at: new Date(), sale }; f.db.financeInstallment.findMany.mockResolvedValue([{ ...base, amount: new Prisma.Decimal('40'), due_on: new Date('2026-01-31'), received_on: new Date('2026-02-02') }, { ...base, id: 'second', number: 2, amount: new Prisma.Decimal('20'), due_on: new Date('2026-02-28'), received_on: null }]); const d = await f.service.dashboard(user, { month: '2026-02', months: 1 }); expect(d.monthly[0]).toMatchObject({ expected: '20.00', received: '40.00', settled: '0.00', pending: '20.00' }); });
    it('blocks other tenant admins at the service boundary', async () => { const f = fixture(); await expect(f.service.dashboard({ ...user, id: 'admin', role: 'SUPER_ADMIN' }, {})).rejects.toBeInstanceOf(ForbiddenException); expect(f.db.financeInstallment.findMany).not.toHaveBeenCalled(); });
});
