'use client';
import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarCheck2, GraduationCap, UserCheck, Target, Plus, Pencil, RefreshCw, RotateCcw, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '@/lib/api';
import { getSocket } from '@/lib/socket';
import { type TeamActivity, type TeamDashboard, type TeamKind, teamDate, teamLabels } from '@/lib/partner-team';
import { Button } from '@/components/ui/button';
import { Field, fieldClass, PartnerModal } from './partner-forms';
import { TeamActivityForm, TeamCancellationForm, TeamGoalForm } from './team-forms';

type Editor = { kind: 'activity'; activity?: TeamActivity; initial: TeamKind } | { kind: 'goal'; consultant?: string } | { kind: 'cancel'; activity: TeamActivity };
export function TeamPerformance({ tenant, userId, role, month }: { tenant: string; userId: string; role: string; month: string }) {
  const [consultant, setConsultant] = useState(''); const [kind, setKind] = useState(''); const [status, setStatus] = useState('active'); const [page, setPage] = useState(1); const [editor, setEditor] = useState<Editor | null>(null);
  const qc = useQueryClient(); const manager = ['SUPER_ADMIN', 'GERENTE'].includes(role); const writable = manager || role === 'OPERADOR';
  const query = useQuery({ queryKey: ['partner-team', tenant, userId, month, consultant, kind, status, page], queryFn: async () => (await api.get<TeamDashboard>('/api/partners/team', { params: { month, consultant_id: consultant || undefined, kind: kind || undefined, status, page } })).data, refetchInterval: 30000 });
  useEffect(() => { const socket = getSocket(); const refresh = () => { void qc.invalidateQueries({ queryKey: ['partner-team', tenant] }); void qc.invalidateQueries({ queryKey: ['partner-team-goal', tenant] }); }; socket.on('partners:updated', refresh); return () => { socket.off('partners:updated', refresh); }; }, [qc, tenant]);
  async function saved() { setEditor(null); toast.success('Registro salvo. Resultados atualizados.'); await Promise.all(['partner-team', 'partner-team-goal', 'partner-team-subjects', 'partners', 'partner-audit', 'partner-candidates'].map(key => qc.invalidateQueries({ queryKey: [key, tenant] }))); }
  const data = query.data;
  return <section className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-xl font-semibold">Desempenho da equipe</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Atividades realizadas e cadastros efetivados em {month.split('-').reverse().join('/')}. Cada resultado pertence à consultora e à data registradas.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" aria-label="Atualizar desempenho" disabled={query.isFetching} onClick={() => void query.refetch()}><RefreshCw className={`h-4 w-4 ${query.isFetching ? 'animate-spin' : ''}`} /></Button>{manager && <Button variant="outline" disabled={!data} onClick={() => setEditor({ kind: 'goal' })}><Target className="mr-2 h-4 w-4" />Definir meta</Button>}{writable && <><Button variant="outline" disabled={!data} onClick={() => setEditor({ kind: 'activity', initial: 'meeting' })}><Plus className="mr-2 h-4 w-4" />Registrar atividade</Button><Button disabled={!data} onClick={() => setEditor({ kind: 'activity', initial: 'registration' })}><UserCheck className="mr-2 h-4 w-4" />Efetivar cadastro</Button></>}</div></div>
    <div className="max-w-sm"><Field label="Consultora"><select className={fieldClass} value={consultant} onChange={e => { setConsultant(e.target.value); setPage(1); }}><option value="">Toda a equipe</option>{data?.members.map(m => <option key={m.id} value={m.id}>{m.name}{m.active ? '' : ' (inativa)'}</option>)}</select></Field></div>
    {query.isLoading && <p role="status" className="py-12 text-center text-muted-foreground">Carregando resultados da equipe…</p>}
    {query.isError && <div role="alert" className="rounded-xl border border-destructive/30 p-5">Não foi possível carregar os resultados. <Button variant="link" onClick={() => void query.refetch()}>Tentar novamente</Button></div>}
    {data && !query.isError && <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
        { label: 'Reuniões realizadas', value: data.summary.meetings, Icon: CalendarCheck2, detail: 'Agendamentos não entram na contagem' },
        { label: 'Cadastros efetivados', value: data.summary.registrations, Icon: UserCheck, detail: 'Cada parceiro conta uma única vez' },
        { label: 'Treinamentos realizados', value: data.summary.trainings, Icon: GraduationCap, detail: 'Concluídos no período selecionado' },
        { label: 'Meta de cadastros', value: data.summary.target ?? '—', Icon: Target, detail: data.summary.goals_configured ? `Soma das metas de ${data.summary.goals_configured} consultora(s)` : 'Nenhuma meta definida para a seleção' },
      ].map(({ label, value, Icon, detail }) => <article key={label} className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between gap-3 text-sm text-muted-foreground"><p>{label}</p><Icon className="h-5 w-5 text-emerald-600" /></div><p className="mt-4 text-3xl font-semibold tabular-nums">{value}</p><p className="mt-2 text-xs text-muted-foreground">{detail}</p></article>)}</div>
      <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><caption className="sr-only">Resultados mensais por consultora</caption><thead className="bg-muted/50 text-muted-foreground"><tr>{['Consultora', 'Reuniões', 'Cadastros efetivados', 'Treinamentos', 'Meta de cadastros', ...(manager ? [''] : [])].map((label, i) => <th key={i} className="whitespace-nowrap p-4 font-medium">{label}</th>)}</tr></thead><tbody>{data.performance.map(row => <tr key={row.id} className="border-t"><td className="p-4 font-medium">{row.name}{!row.active && <span className="ml-2 text-xs font-normal text-muted-foreground">Inativa</span>}</td><td className="p-4 tabular-nums">{row.meetings}</td><td className="p-4 font-semibold tabular-nums">{row.registrations}</td><td className="p-4 tabular-nums">{row.trainings}</td><td className="min-w-[210px] p-4">{row.target === null ? <span className="text-muted-foreground">Não definida</span> : <><div className="flex justify-between gap-3"><span>{row.registrations} de {row.target}</span><strong>{row.percentage === null ? '—' : `${row.percentage.toLocaleString('pt-BR')}%`}</strong></div><div className="my-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${Math.min(100, row.percentage ?? 0)}%` }} /></div><p className="text-xs text-muted-foreground">{row.target === 0 ? 'Meta configurada como zero' : row.remaining === 0 ? 'Meta atingida' : `Faltam ${row.remaining} cadastros`}</p></>}</td>{manager && <td className="p-4"><Button variant="ghost" size="sm" onClick={() => setEditor({ kind: 'goal', consultant: row.id })}><Pencil className="mr-2 h-3 w-3" />Meta</Button></td>}</tr>)}</tbody></table>{!data.performance.length && <p className="p-8 text-center text-sm text-muted-foreground">Nenhuma consultora com atividade ou meta nesta seleção.</p>}</div>
      <div className="rounded-lg bg-muted/40 px-4 py-3 text-sm text-muted-foreground">Um contato no Kanban ou um parceiro antigo não entra automaticamente na meta. Use <strong>Efetivar cadastro</strong> para confirmar a empresa, a consultora e a data. Alterar a coluna do Kanban não soma novas atividades.</div>
      <section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold">Histórico de atividades</h3><p className="text-sm text-muted-foreground">{data.history.total} registro(s) nos filtros abaixo. Os cartões acima consideram todas as atividades válidas do mês.</p></div><div className="flex flex-wrap gap-3"><Field label="Tipo"><select className={fieldClass} value={kind} onChange={e => { setKind(e.target.value); setPage(1); }}><option value="">Todos os tipos</option>{Object.entries(teamLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Situação"><select className={fieldClass} value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="active">Válidas</option><option value="cancelled">Canceladas</option><option value="all">Todas</option></select></Field></div></div>
        <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted/50 text-muted-foreground"><tr>{['Data', 'Atividade / empresa', 'Consultora', 'Situação', ...(writable ? [''] : [])].map((label, i) => <th key={i} className="whitespace-nowrap p-4 font-medium">{label}</th>)}</tr></thead><tbody>{data.history.rows.map(row => <tr key={row.id} className={`border-t ${row.cancelled ? 'text-muted-foreground' : ''}`}><td className="whitespace-nowrap p-4">{teamDate(row.occurred_on)}{row.kind !== 'registration' && <p className="text-xs text-muted-foreground">{row.occurred_time}</p>}</td><td className="p-4"><p className="font-medium">{teamLabels[row.kind]}</p><p>{row.company_name}</p>{row.note && <p className="mt-1 max-w-md whitespace-pre-wrap text-xs text-muted-foreground">{row.note}</p>}</td><td className="p-4">{data.members.find(m => m.id === row.consultant_id)?.name ?? row.consultant_name}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs ${row.cancelled ? 'bg-muted' : 'bg-emerald-500/10 text-emerald-600'}`}>{row.cancelled ? 'Cancelada' : 'Contabilizada'}</span></td>{writable && <td className="whitespace-nowrap p-4">{(manager || row.consultant_id === userId) && <>{!row.cancelled && <Button variant="ghost" size="sm" onClick={() => setEditor({ kind: 'activity', initial: row.kind, activity: row })}><Pencil className="mr-2 h-3 w-3" />Corrigir</Button>}<Button variant="ghost" size="sm" onClick={() => setEditor({ kind: 'cancel', activity: row })}>{row.cancelled ? <RotateCcw className="mr-2 h-3 w-3" /> : <XCircle className="mr-2 h-3 w-3" />}{row.cancelled ? 'Restaurar' : 'Cancelar'}</Button></>}</td>}</tr>)}</tbody></table>{!data.history.rows.length && <p className="p-10 text-center text-sm text-muted-foreground">Nenhuma atividade neste período com os filtros selecionados.</p>}</div>
        <div className="flex items-center justify-between gap-3 text-sm"><span>Página {page} de {data.history.pages}</span><div className="flex gap-2"><Button variant="outline" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Anterior</Button><Button variant="outline" disabled={page >= data.history.pages} onClick={() => setPage(p => p + 1)}>Próxima</Button></div></div>
      </section>
    </>}
    {editor && data && <PartnerModal close={() => setEditor(null)} title={editor.kind === 'goal' ? 'Meta individual de cadastros' : editor.kind === 'cancel' ? editor.activity.cancelled ? 'Restaurar atividade' : 'Cancelar atividade' : editor.activity ? 'Corrigir atividade' : editor.initial === 'registration' ? 'Efetivar cadastro' : 'Registrar atividade realizada'} description={editor.kind === 'goal' ? 'Defina a quantidade de novos cadastros para a consultora neste mês.' : 'Os registros são vinculados à consultora e ficam no histórico.'}>
      {editor.kind === 'activity' && <TeamActivityForm row={editor.activity} initialKind={editor.initial} members={data.members} userId={userId} manager={manager} today={data.today} tenant={tenant} saved={saved} />}
      {editor.kind === 'goal' && <TeamGoalForm month={month} members={data.members} tenant={tenant} initialConsultant={editor.consultant} saved={saved} />}
      {editor.kind === 'cancel' && <TeamCancellationForm row={editor.activity} saved={saved} />}
    </PartnerModal>}
  </section>;
}
