ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_tenant_id_fkey";
ALTER TABLE "User" ADD CONSTRAINT "User_tenant_id_fkey"
  FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE
  DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "Tenant" DROP CONSTRAINT IF EXISTS "Tenant_owner_id_fkey";
ALTER TABLE "Tenant" ADD CONSTRAINT "Tenant_owner_id_fkey"
  FOREIGN KEY ("owner_id") REFERENCES "User"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE
  DEFERRABLE INITIALLY DEFERRED;
