BEGIN;
ALTER TABLE "LeadView" ADD COLUMN IF NOT EXISTS "tipo_padrao" TEXT NOT NULL DEFAULT 'kanban';
ALTER TABLE "LeadView" ADD COLUMN IF NOT EXISTS "sort" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "LeadView" ADD COLUMN IF NOT EXISTS "colunas" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "LeadView" ADD COLUMN IF NOT EXISTS "card_fields" JSONB NOT NULL DEFAULT '[]';
COMMIT;
